keys:
  - &dasehak age1a7jpt9qpqs69untz8sadycju3sqjwd072uah6zn9g0dnpt43kytqdey2jf
  - &nyax age1ml8nsgskn56x8uv9pncvly8gy2qna4dhuk2rfp289eq6qgq5ku6sszr2zy
creation_rules:
  - path_regex: secrets/sops/secrets.yaml$
    key_groups:
    - age:
      - *dasehak
      - *nyax