keys:
  - &dasehak age17qf63acqkyz46vjsalx6u7xlhm0c0cq0akxcw0jhxsyn4z4vjgtqj6xpax
  - &nyax age1fej6h0qprmpv5s76m6pllt0cv9qmkenpp7parcn9f5teem9hgyuqlftjkp
creation_rules:
  - path_regex: secrets/sops/secrets.yaml$
    key_groups:
    - age:
      - *dasehak
      - *nyax